Word:
  path: webservice/word
  properties:
    id: String
    value: String
    reading: String
    isCommon: bool
    priority: int?
    difficultyGrade: DifficultyGrade
    meaningEntries: List<MeaningEntry>

MeaningEntry:
  path: webservice/word
  properties:
    typeString: String
    type: WordType?
    misc: String?
    meanings: List<String>

DifficultyGrade:
  path: enum/difficulty_grade.dart
  type: custom

WordType:
  path: enum/wordtype.dart
  type: custom

## PROFILE

UserData:
  path: webservice/user
  properties:
    id: String
    userName: String
    photo: String?
    userColor: int?
