Word:
  path: webservice/word
  properties:
    id: String
    value: String
    reading: String
    isCommon: bool
    priority: int?
    jlpt: Jlpt?
    meaningEntries: List<MeaningEntry>

MeaningEntry:
  path: webservice/word
  properties:
    typeString: String
    type: WordType?
    misc: String?
    meanings: List<String>

Jlpt:
  path: enum/jlpt.dart
  type: custom

WordType:
  path: enum/wordtype.dart
  type: custom